group entry and group rewards
cardinal-labs/cardinal-staking pull request #290
Opened 2022-10-19 14:42 UTC by soroshansari

2022-10-24 15:32 UTC, jpbogle commented
rebased the branch

2022-10-27 23:24 UTC, jpbogle commented on programs/cardinal-stake-pool/src/instructions/init_group_entry.rs
> +    group_entry.id = ctx.accounts.id.key();
dont think we need to store this if its never read from? or why do we want this?

2022-10-27 23:25 UTC, jpbogle commented on programs/cardinal-stake-pool/src/instructions/remove_from_group_entry.rs
> +    if group_entry.min_group_days.is_some() && (Clock::get().unwrap().unix_timestamp - group_entry.started_at) < (group_entry.min_group_days.unwrap() * 24 * 60 * 60) as i64 {
I think well be better off storing this as a minimum_group_seconds

2022-10-27 23:25 UTC, jpbogle commented on programs/cardinal-stake-pool/src/instructions/remove_from_group_entry.rs
> +    if group_entry.min_group_days.is_some() && (Clock::get().unwrap().unix_timestamp - group_entry.started_at) < (group_entry.min_group_days.unwrap() * 24 * 60 * 60) as i64 {
curious what the use case is if the user gets to decide this value as well by passing it in when they init_group_entry

2022-10-27 23:26 UTC, jpbogle commented on programs/cardinal-stake-pool/src/instructions/add_to_group_entry.rs
> +    group_entry.started_at = Clock::get().unwrap().unix_timestamp;
this value isnt really started_at but actually `changed_at` right?

2022-10-27 23:33 UTC, jpbogle commented
@soroshansari stake_pool changes in general LGTM

Will want to do 1 pass to make sure the boolean added at the end of stake_entry will not collide with any data on the end of the stake_entry

This can happen if the data was previously long, and then got shortened (optional got removed) the boolean can collide with some residual data there that didnt get zeroed out



---

1 main question i have is what is the logic behind making group-reward-distributor and what features does it have. Can u summarize how it works specifically? Originally was thinking you would just use the update_authority of the reward distributor to change the multipliers for grouped vs non-grouped entries

2022-10-28 14:08 UTC, soroshansari commented on programs/cardinal-stake-pool/src/instructions/remove_from_group_entry.rs
> +    if group_entry.min_group_days.is_some() && (Clock::get().unwrap().unix_timestamp - group_entry.started_at) < (group_entry.min_group_days.unwrap() * 24 * 60 * 60) as i64 {
Well, we plan to have 3 different reward distributors. One with no limits, the others with 3 and 6 months minimum lock time. So here we can store the minimum period, and then in the reward distributor, we will check this time. If it has not met the distributor requirements they won't be able to create the reward entry.

2022-10-28 14:13 UTC, soroshansari commented on programs/cardinal-stake-pool/src/instructions/add_to_group_entry.rs
> +    group_entry.started_at = Clock::get().unwrap().unix_timestamp;
That was one of my initial thoughts. But I think started_at is still valid because the start time will be when the last NFT is added to the group. So when the user adds a new NFT to the group, the start time will be reset. And it won't be affected by other scenarios like removing one from the group. But if you think `changed_at` is still a better term here, I have no obligation to change it.

2022-10-28 14:28 UTC, soroshansari commented
@jpbogle well, based on our requirements, we needed a separate reward distributor, which I named `group-reward-distributor`.  
First, we don't want to mess with the current rewards that each NFT can take. And we wanted to have something on top of that, even with another token. So, for example, the NFT rewards can be based on Block, and then the set reward can be based on Assets. 
Second, the users can claim their group rewards separately from their NFT rewards. And this will give us the ability to have separate lockdown periods and so different reward rates.
Third, we implemented another logic for multiplying the rewards by the total number of sets each user has. So in this way, when a user group, let's say, two sets of NFTs, instead of claiming 2x rewards, they can claim, let's say, 2.3x rewards.

2022-10-28 15:07 UTC, soroshansari commented on programs/cardinal-stake-pool/src/instructions/init_group_entry.rs
> +    group_entry.id = ctx.accounts.id.key();
Yeah makes sense. I'll remove it.

2022-10-28 17:34 UTC, gchatz22 requested changes
some initial thoughts here, on a plane right now and my laptop is about to die, will continue with more notes that i have :)

2022-10-31 10:27 UTC, soroshansari commented on programs/cardinal-group-reward-distributor/src/state.rs
> +    pub reward_kind: u8,
Good idea. I'll implement it this way.

2022-10-31 10:28 UTC, soroshansari commented on programs/cardinal-group-reward-distributor/src/instructions/init_group_reward_distributor.rs
> +    id: AccountInfo<'info>,
Makes sense.

2022-11-02 13:59 UTC, gchatz22 requested changes
Left a couple suggestions + questions I have that would be great to get some clarification. A couple more things that we would need

1. Could you pull in the latest changes from main branch?
2. Could we get some tests going? This PR is pretty big and would need a good amount of thorough tests to get this merged (will definitely work with you to fine-tune the tests). I have a pretty good understanding of this PR a this point and majority looks 👍. I believe good tests are going to dig out a good amount of issues :)

2022-11-02 13:59 UTC, gchatz22 commented on programs/cardinal-stake-pool/src/instructions/remove_from_group_entry.rs
> +    if group_entry.min_group_days.is_some() && (Clock::get().unwrap().unix_timestamp - group_entry.started_at) < (group_entry.min_group_days.unwrap() * 24 * 60 * 60) as i64 {
+1 on `minimum_group_seconds`. although we understand most usecases will be utilizing days for months, everything time related is in seconds and provides more usage (you can always make days from seconds but not the other way around)

2022-11-02 13:59 UTC, gchatz22 commented on programs/cardinal-group-reward-distributor/src/instructions/claim_group_rewards.rs
> +        if group_entry.min_group_days.is_some() {
maybe misunderstanding this, is `min_group_days` supposed to be a minimum amount of time you need the tokens to be grouped for, or the amount of time a group is going to receive no matter how much time the actual tokens where grouped for?

2022-11-03 14:00 UTC, soroshansari commented on programs/cardinal-group-reward-distributor/src/instructions/claim_group_rewards.rs
> +        if group_entry.min_group_days.is_some() {
Well, min_group_days is an optional field that, if it exists, will prevent them from regrouping sooner than that time. I kept it as days because we will use it as a multiplier on the group reward distributor (GRD). So, for example, if it is set to 6 and on the GRD, the daily multiplier is set to, let's say 0.3, we will reward them 1.8 times what they could receive without it. It's possible to keep it as seconds and then un the multiplier part and divide it by the number of seconds in a day. But I thought keeping it this way could simplify the process.

2022-11-03 14:05 UTC, soroshansari commented on programs/cardinal-stake-pool/src/instructions/init_group_entry.rs
> +    stake_entry: Box<Account<'info, StakeEntry>>,
I initially thought so, but it seems to me it can feel a bit wired to have a group without any entry. But if you think this can make the process more understandable, I can make it this way.

2022-11-03 17:27 UTC, gchatz22 commented on programs/cardinal-group-reward-distributor/src/instructions/claim_group_rewards.rs
> +        if group_entry.min_group_days.is_some() {
hmm not sure i am understanding fully (maybe im thinking it incorrectly apologies), but on a high level everything that handles time is measured in seconds for composability so would love to see this too with `min_group_days` --> `min_group_seconds`

2022-11-03 17:27 UTC, gchatz22 commented on programs/cardinal-stake-pool/src/instructions/init_group_entry.rs
> +    stake_entry: Box<Account<'info, StakeEntry>>,
i do think the suggested approach makes sense, because even in `remove_from_group_entry.rs` if you remove an element from an array of length 1 you have an empty array `group_entry`. i guess you could check that and close the `group_entry` is so, but i still think having an empty a group entry is ok

2022-11-04 12:48 UTC, soroshansari commented on programs/cardinal-stake-pool/src/instructions/init_group_entry.rs
> +    stake_entry: Box<Account<'info, StakeEntry>>,
Yeah makes sense.

2022-11-22 05:05 UTC, jpbogle commented
rebased PR and fixed tests

2022-11-22 06:00 UTC, jpbogle commented
also did some checks and we need to do a migration to add grouped boolean since some stake_entries have data there that would collide with adding that new field

2022-12-13 22:59 UTC, gchatz22 commented
rebasing main, will look into merging in a bit

2022-12-13 23:42 UTC, merged