fix: group entry
cardinal-labs/cardinal-staking pull request #353
Opened 2023-01-06 14:50 UTC by soroshansari

2023-01-09 16:47 UTC, gchatz22 requested changes

2023-01-09 16:47 UTC, gchatz22 commented on programs/cardinal-stake-pool/src/instructions/groups/remove_from_group_entry.rs
> -    let new_group_entry = GroupStakeEntry {
not sure why you are removing the logic for resizing the accounts. i guess you do not need to resize it when removing from group entry but its good practice every time you change the group reward entry to resize the account same way we do on `add_to_group_entry`

2023-01-09 16:47 UTC, gchatz22 commented on programs/cardinal-stake-pool/src/instructions/groups/remove_from_group_entry.rs
> +    if group_entry.group_cooldown_start_seconds.is_none() || ((Clock::get().unwrap().unix_timestamp - group_entry.group_cooldown_start_seconds.unwrap()) as u32) < group_entry.group_cooldown_seconds {
so this basically you want to error any group entry that does not have `group_cooldown_start_seconds`? thats how im interpreting the first condition at least

2023-01-09 16:47 UTC, gchatz22 commented on programs/cardinal-stake-pool/src/instructions/groups/remove_from_group_entry.rs
> +    if group_entry.group_cooldown_start_seconds.is_none() || ((Clock::get().unwrap().unix_timestamp - group_entry.group_cooldown_start_seconds.unwrap()) as u32) < group_entry.group_cooldown_seconds {
i think you basically want to say if there are cooldown start seconds and there are still some remaning you want to error

2023-01-09 16:48 UTC, gchatz22 commented on programs/cardinal-group-reward-distributor/src/instructions/claim_group_rewards.rs
> +    let end_time_stamp = if group_entry.group_cooldown_start_seconds.is_some() {
would suggest this instead, looks more clean ;)

```let end_time_stamp = group_entry.group_cooldown_start_seconds.unwrap_or(Clock::get().unwrap().unix_timestamp);```

2023-01-09 16:57 UTC, soroshansari commented on programs/cardinal-stake-pool/src/instructions/groups/remove_from_group_entry.rs
> +    if group_entry.group_cooldown_start_seconds.is_none() || ((Clock::get().unwrap().unix_timestamp - group_entry.group_cooldown_start_seconds.unwrap()) as u32) < group_entry.group_cooldown_seconds {
To fix the previous issue, I've changed the logic to first `init_ungrouping` get called, which will set the `group_cooldown_start_seconds` and then subsequent `remove_from_group_entry`s will get called. So here we through an error on two conditions: 
1) there is no group_cooldown_start_seconds that has been set 
2) Or the group_cooldown_seconds has not been met (Take note that the default value for group_cooldown_seconds is zero)

2023-01-09 17:11 UTC, soroshansari commented on programs/cardinal-stake-pool/src/instructions/groups/remove_from_group_entry.rs
> -    let new_group_entry = GroupStakeEntry {
I removed this to simplify the process since after calling `init_ungrouping`, users won't be able to add more to the entry, and they can only call `remove_from_group_entrys`. Also, I added logic for `group_entry` to get closed on removing the last entry.

2023-01-11 17:37 UTC, gchatz22 commented on programs/cardinal-stake-pool/src/instructions/groups/remove_from_group_entry.rs
> -    let new_group_entry = GroupStakeEntry {
i see re: closing the account. okay sure, although for good practice would be cool to add back the resizing

2023-01-12 11:06 UTC, soroshansari commented on programs/cardinal-stake-pool/src/instructions/groups/remove_from_group_entry.rs
> +    if group_entry.group_cooldown_start_seconds.is_none() || ((Clock::get().unwrap().unix_timestamp - group_entry.group_cooldown_start_seconds.unwrap()) as u32) < group_entry.group_cooldown_seconds {
@gchatz22 I've added resizing the account to `remove_from_group_entry` if the account is not closing

2023-01-12 11:07 UTC, soroshansari commented on programs/cardinal-stake-pool/src/instructions/groups/remove_from_group_entry.rs
> +    if group_entry.group_cooldown_start_seconds.is_none() || ((Clock::get().unwrap().unix_timestamp - group_entry.group_cooldown_start_seconds.unwrap()) as u32) < group_entry.group_cooldown_seconds {
Yeah that's an intended logic

2023-01-12 18:37 UTC, gchatz22 commented on programs/cardinal-stake-pool/src/instructions/groups/remove_from_group_entry.rs
> -    let new_group_entry = GroupStakeEntry {
👍🏼

2023-01-12 18:37 UTC, merged